config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'user#home'
  get 'users/edit' => 'registrations#edit'
  
  get '/user/edit/:user_id' => 'user#edit'
  post '/user/update/:user_id' => 'user#update'
  
  get 'about-me' => 'user#about-me'
  get '/:user_id/diary' => 'meetings#index'
  
  get '/user/info' => 'user#info'

  get '/subjects/subject_add'=>'subjects#subject_add'
  post '/subjects/subject_add'=>'subjects#subject_add_new'
  get '/subjects/subject_delete/:s_id'=> 'subjects#subject_delete'
  get '/subjects/subject_list' => 'subjects#subject_list'
  get '/subjects/subject_list/:subject_id' => 'subjects#subject_list'
  
  post '/subjects/subject_list/:subject_id' => 'subjects#subject_list'
  get '/subjects/show'
  
  post '/subjects/update/:subject_id' => 'subjects#update'
  
  get '/contents/content_list' => 'contents#content_list'
  get '/contents/new/:subject_id' => 'contents#new'
  post '/contents/create/:subject_id' => 'contents#create'
  
  get '/contents/detail/:content_id' => 'contents#detail'
  post '/contents/update/:subject_id/:content_id' => 'contents#update'
  get '/detail/edit/:subject_id/:content_id' => 'contents#edit'
  get '/detail/delete/:content_id' => 'contents#delete'
  get '/contents/review' => 'contents#review'
  
  get '/:subject_id/questions/solv_question' => 'questions#solv_question'
  post '/:subject_id/questions/solv_question' => 'questions#solv_question'
    
  get '/:subject_id/questions/choice' => 'questions#choice'
  post '/:subject_id/questions/choice' => 'questions#choice'
  get '/:subject_id/questions/longQ' => 'questions#longQ'
  post '/:subject_id/questions/longQ' => 'questions#longQ'
  get '/:subject_id/questions/shortQ' => 'questions#shortQ'
  post '/:subject_id/questions/shortQ' => 'questions#shortQ'
  post '/:subject_id/questions/wrongQ' => 'questions#wrongQ'
  
  post '/:subject_id/:user_id/fail_question/add' => 'fail_question#add'
  get '/fail_question/show/:subject_id' => 'fail_question#show'

  

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
    belongs_to :User 
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    if (current_user.email == "admin@email.com")
      @subjects = Subject.all
      @meetings = Meeting.all
    else
      @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").distinct
      @meetings = Meeting.where(user_id: current_user.id)
    end

  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    
  end

  # GET /meetings/new
  def new
    if(current_user.email == "admin@email.com")
        @subjects = Subject.all
    else
        @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").distinct
    end
    @meeting = Meeting.new
    
  end

  # GET /meetings/1/edit
  def edit
    if(current_user.email == "admin@email.com")
        @subjects = Subject.all
    else
        @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").all
    end
  end

  # POST /meetings
  # POST /meetings.json
  def create
    
    if(current_user.email == "admin@email.com")
        @subjects = Subject.all
    else
        @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").distinct
    end
    
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        # format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        # format.json { render :index, status: :created, location: @meeting }
        format.html { redirect_to meetings_url}
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def edit
    if(current_user.email == "admin@email.com")
      @subjects = Subject.all
    else
      @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").distinct
    end
  end
  
  def update
    
    if(current_user.email == "admin@email.com")
      @subjects = Subject.all
    else
      @subjects = Subject.joins("INNER JOIN studies ON studies.subject_id = subjects.id AND studies.user_id = '#{current_user.id}'").distinct
    end
    
    respond_to do |format|
      if @meeting.update(meeting_params)
        # format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        # format.json { render :show, status: :ok, location: @meeting }
        format.html { redirect_to meetings_url, notice: @meeting.start_time.in_time_zone("Asia/Seoul").strftime("%F")+' 이벤트가 성공적으로 갱신되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: @meeting.start_time.in_time_zone("Asia/Seoul").strftime("%F")+' 이벤트가 성공적으로 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time)
    end
  
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <!-- 에러처리 -->
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- /에러처리 -->
  
  <body style="background:#f4f4f4">
      <div class="container-fluid" style="width:90%; background:#fff">
          <div class="portfolio-content col-md-10 col-md-offset-1">
              <div class="row" style="margin:10pt;">
                  
                    <div class="cbp-l-project-desc pull-right" style="padding-top:20pt">
                      <p style="float:right;"><%= link_to 'Back', meetings_path %></p>
                      <ul class="cbp-l-project-details-list" style="margin-left:-250px">
                        <li><strong>Subject</strong>
                        <%= f.select :name, @subjects.pluck(:sub_name) %></li>
                        <li><strong>Start Time</strong>
                        <%= f.datetime_select :start_time %></li>
                        <li><strong>End Time</strong>
                        <%= f.datetime_select :end_time %></li>
                      </ul>
                      <button type="submit" class="btn btn-outline-secondary" style="float:right;">저장하기</button>      
                  </div>
              </div>
        </div>
      </div>
  </body>
<% end %>

app/views/meetings/edit.html.erb
<body style="background:#f4f4f4">
  <div class="container-fluid" style="width:90%; background:#fff">
    <div class="portfolio-content col-md-10 col-md-offset-1">
        <div class="row" style="margin:10pt;">
            <h1 align="center">Editing Meeting</h1>
            <center><p> 과목과 날짜를 자유롭게 수정이 가능합니다 </p></center>
            <%= render 'form' %>
        </div>
    </div>
  </div>
</body>

   

app/views/meetings/index.html.erb
<head>
  <style>
    .btn-sched{
      color: #fff;
      background-color: #e6a394;
      border-color: #fff;
      display: inline-block;
      padding: 6px 12px;
      margin-bottom: 0;
      font-size: 14px;
      font-weight: 400;
      line-height: 1.42857143;
      text-align: center;
      white-space: nowrap;
      vertical-align: middle;
      -ms-touch-action: manipulation;
      touch-action: manipulation;
      cursor: pointer;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
      background-image: none;
      border: 1px solid transparent;
      border-radius: 4px;
    }
  </style>
</head>

<body style="background:#f4f4f4">
  <div class="container" style="width:90%; background:#fff">
    <p id="notice"><%= notice %></p>
  
    <center><h2>Study Planner</h2></center>
    <center>
      <p>스터디 플래너입니다<br> 일정을 추가하고 싶으시면, New Study를 눌러주세요!</p>
    </center>
    <br>
    
    <button type="button" class="btn-sched" style="float:right;"><%= link_to 'New Study', new_meeting_path %></button>
    <br><br>
    
    <%= month_calendar events: @meetings do |date, meetings| %>
     <%= date.day %>
      <% meetings.each do |meeting| %>
        <div>
          <%= meeting.name %>
          <%= link_to 'Edit', edit_meeting_path(meeting) %>
          <%= link_to 'Destroy', meeting, method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      <% end %>
    <% end %>
  
  </div>
</body>

app/views/meetings/new.html.erb
<body style="background:#f4f4f4">
  <div class="container-fluid" style="width:90%; background:#fff">
    <div class="portfolio-content col-md-10 col-md-offset-1">
        <div class="row" style="margin:10pt;">
            <h1 align="center">Add Your Study Schedule</h1>
            <center><p> 공부해야하는 과목과 날짜를 정해서 계획을 세워보세요!  </p></center>
            <%= render 'form' %>
        </div>
    </div>
  </div>
</body>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>